name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            # always run Linux (cheapest)
          - os: macos-latest
            # only on main (10x minute multiplier)
            main-only: true
          - os: windows-latest
            # only on main (2x minute multiplier)
            main-only: true
    runs-on: ${{ matrix.os }}
    if: ${{ !matrix.main-only || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - run: npx vitest run
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/dist
